package com.bruce.designer.model;

import java.util.Date;

public class AlbumRecommend {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_recommend.id
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_recommend.album_id
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_recommend.sort
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_recommend.create_time
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_recommend.update_time
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_recommend.id
	 * @return  the value of tb_album_recommend.id
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_recommend.id
	 * @param id  the value for tb_album_recommend.id
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_recommend.album_id
	 * @return  the value of tb_album_recommend.album_id
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_recommend.album_id
	 * @param albumId  the value for tb_album_recommend.album_id
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_recommend.sort
	 * @return  the value of tb_album_recommend.sort
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_recommend.sort
	 * @param sort  the value for tb_album_recommend.sort
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_recommend.create_time
	 * @return  the value of tb_album_recommend.create_time
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_recommend.create_time
	 * @param createTime  the value for tb_album_recommend.create_time
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_recommend.update_time
	 * @return  the value of tb_album_recommend.update_time
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_recommend.update_time
	 * @param updateTime  the value for tb_album_recommend.update_time
	 * @mbggenerated  Sun Aug 24 14:23:50 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}