package com.bruce.designer.model;

import java.util.Date;

public class AlbumSlide {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.remark
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.album_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.user_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.is_cover
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Short isCover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.slide_large_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String slideLargeImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.slide_medium_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String slideMediumImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.slide_small_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String slideSmallImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String wxShareTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String wxShareContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String wxShareIconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.status
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.create_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.update_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.id
	 * @return  the value of tb_album_slide.id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.id
	 * @param id  the value for tb_album_slide.id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.title
	 * @return  the value of tb_album_slide.title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.title
	 * @param title  the value for tb_album_slide.title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.remark
	 * @return  the value of tb_album_slide.remark
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.remark
	 * @param remark  the value for tb_album_slide.remark
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.album_id
	 * @return  the value of tb_album_slide.album_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.album_id
	 * @param albumId  the value for tb_album_slide.album_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.user_id
	 * @return  the value of tb_album_slide.user_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.user_id
	 * @param userId  the value for tb_album_slide.user_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.is_cover
	 * @return  the value of tb_album_slide.is_cover
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Short getIsCover() {
		return isCover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.is_cover
	 * @param isCover  the value for tb_album_slide.is_cover
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setIsCover(Short isCover) {
		this.isCover = isCover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.slide_large_img
	 * @return  the value of tb_album_slide.slide_large_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getSlideLargeImg() {
		return slideLargeImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.slide_large_img
	 * @param slideLargeImg  the value for tb_album_slide.slide_large_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setSlideLargeImg(String slideLargeImg) {
		this.slideLargeImg = slideLargeImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.slide_medium_img
	 * @return  the value of tb_album_slide.slide_medium_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getSlideMediumImg() {
		return slideMediumImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.slide_medium_img
	 * @param slideMediumImg  the value for tb_album_slide.slide_medium_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setSlideMediumImg(String slideMediumImg) {
		this.slideMediumImg = slideMediumImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.slide_small_img
	 * @return  the value of tb_album_slide.slide_small_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getSlideSmallImg() {
		return slideSmallImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.slide_small_img
	 * @param slideSmallImg  the value for tb_album_slide.slide_small_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setSlideSmallImg(String slideSmallImg) {
		this.slideSmallImg = slideSmallImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.wx_share_title
	 * @return  the value of tb_album_slide.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getWxShareTitle() {
		return wxShareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.wx_share_title
	 * @param wxShareTitle  the value for tb_album_slide.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setWxShareTitle(String wxShareTitle) {
		this.wxShareTitle = wxShareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.wx_share_content
	 * @return  the value of tb_album_slide.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getWxShareContent() {
		return wxShareContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.wx_share_content
	 * @param wxShareContent  the value for tb_album_slide.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setWxShareContent(String wxShareContent) {
		this.wxShareContent = wxShareContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.wx_share_icon_url
	 * @return  the value of tb_album_slide.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getWxShareIconUrl() {
		return wxShareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.wx_share_icon_url
	 * @param wxShareIconUrl  the value for tb_album_slide.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setWxShareIconUrl(String wxShareIconUrl) {
		this.wxShareIconUrl = wxShareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.status
	 * @return  the value of tb_album_slide.status
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.status
	 * @param status  the value for tb_album_slide.status
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.create_time
	 * @return  the value of tb_album_slide.create_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.create_time
	 * @param createTime  the value for tb_album_slide.create_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.update_time
	 * @return  the value of tb_album_slide.update_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.update_time
	 * @param updateTime  the value for tb_album_slide.update_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}