package com.bruce.designer.model;

import java.util.Date;

public class Album extends AlbumBase{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.remark
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.price
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.link
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.user_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.cover_large_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String coverLargeImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.cover_small_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String coverSmallImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.cover_medium_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String coverMediumImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String wxShareTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String wxShareContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private String wxShareIconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.status
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.create_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.update_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.id
	 * @return  the value of tb_album.id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.id
	 * @param id  the value for tb_album.id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.title
	 * @return  the value of tb_album.title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.title
	 * @param title  the value for tb_album.title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.remark
	 * @return  the value of tb_album.remark
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.remark
	 * @param remark  the value for tb_album.remark
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.price
	 * @return  the value of tb_album.price
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.price
	 * @param price  the value for tb_album.price
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.link
	 * @return  the value of tb_album.link
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.link
	 * @param link  the value for tb_album.link
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.user_id
	 * @return  the value of tb_album.user_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.user_id
	 * @param userId  the value for tb_album.user_id
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.cover_large_img
	 * @return  the value of tb_album.cover_large_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getCoverLargeImg() {
		return coverLargeImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.cover_large_img
	 * @param coverLargeImg  the value for tb_album.cover_large_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setCoverLargeImg(String coverLargeImg) {
		this.coverLargeImg = coverLargeImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.cover_small_img
	 * @return  the value of tb_album.cover_small_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getCoverSmallImg() {
		return coverSmallImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.cover_small_img
	 * @param coverSmallImg  the value for tb_album.cover_small_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setCoverSmallImg(String coverSmallImg) {
		this.coverSmallImg = coverSmallImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.cover_medium_img
	 * @return  the value of tb_album.cover_medium_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getCoverMediumImg() {
		return coverMediumImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.cover_medium_img
	 * @param coverMediumImg  the value for tb_album.cover_medium_img
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setCoverMediumImg(String coverMediumImg) {
		this.coverMediumImg = coverMediumImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.wx_share_title
	 * @return  the value of tb_album.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getWxShareTitle() {
		return wxShareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.wx_share_title
	 * @param wxShareTitle  the value for tb_album.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setWxShareTitle(String wxShareTitle) {
		this.wxShareTitle = wxShareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.wx_share_content
	 * @return  the value of tb_album.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getWxShareContent() {
		return wxShareContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.wx_share_content
	 * @param wxShareContent  the value for tb_album.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setWxShareContent(String wxShareContent) {
		this.wxShareContent = wxShareContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.wx_share_icon_url
	 * @return  the value of tb_album.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public String getWxShareIconUrl() {
		return wxShareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.wx_share_icon_url
	 * @param wxShareIconUrl  the value for tb_album.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setWxShareIconUrl(String wxShareIconUrl) {
		this.wxShareIconUrl = wxShareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.status
	 * @return  the value of tb_album.status
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.status
	 * @param status  the value for tb_album.status
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.create_time
	 * @return  the value of tb_album.create_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.create_time
	 * @param createTime  the value for tb_album.create_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.update_time
	 * @return  the value of tb_album.update_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.update_time
	 * @param updateTime  the value for tb_album.update_time
	 * @mbggenerated  Tue Dec 09 18:39:02 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}