package com.bruce.designer.model;

import java.util.Date;

public class AlbumCounter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.id
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.album_id
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.browse_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Integer browseCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.comment_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Integer commentCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.like_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Integer likeCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.favorite_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Integer favoriteCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.create_time
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_counter.update_time
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.id
	 * @return  the value of tb_album_counter.id
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.id
	 * @param id  the value for tb_album_counter.id
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.album_id
	 * @return  the value of tb_album_counter.album_id
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.album_id
	 * @param albumId  the value for tb_album_counter.album_id
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.browse_count
	 * @return  the value of tb_album_counter.browse_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Integer getBrowseCount() {
		return browseCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.browse_count
	 * @param browseCount  the value for tb_album_counter.browse_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setBrowseCount(Integer browseCount) {
		this.browseCount = browseCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.comment_count
	 * @return  the value of tb_album_counter.comment_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Integer getCommentCount() {
		return commentCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.comment_count
	 * @param commentCount  the value for tb_album_counter.comment_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setCommentCount(Integer commentCount) {
		this.commentCount = commentCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.like_count
	 * @return  the value of tb_album_counter.like_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Integer getLikeCount() {
		return likeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.like_count
	 * @param likeCount  the value for tb_album_counter.like_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setLikeCount(Integer likeCount) {
		this.likeCount = likeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.favorite_count
	 * @return  the value of tb_album_counter.favorite_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Integer getFavoriteCount() {
		return favoriteCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.favorite_count
	 * @param favoriteCount  the value for tb_album_counter.favorite_count
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setFavoriteCount(Integer favoriteCount) {
		this.favoriteCount = favoriteCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.create_time
	 * @return  the value of tb_album_counter.create_time
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.create_time
	 * @param createTime  the value for tb_album_counter.create_time
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_counter.update_time
	 * @return  the value of tb_album_counter.update_time
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_counter.update_time
	 * @param updateTime  the value for tb_album_counter.update_time
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}