package com.bruce.designer.model;

import java.util.Date;

public class Feedback {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_feedback.id
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_feedback.title
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_feedback.content
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_feedback.from_id
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	private Integer fromId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_feedback.status
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_feedback.create_time
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_feedback.update_time
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_feedback.id
	 * @return  the value of tb_feedback.id
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_feedback.id
	 * @param id  the value for tb_feedback.id
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_feedback.title
	 * @return  the value of tb_feedback.title
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_feedback.title
	 * @param title  the value for tb_feedback.title
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_feedback.content
	 * @return  the value of tb_feedback.content
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_feedback.content
	 * @param content  the value for tb_feedback.content
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_feedback.from_id
	 * @return  the value of tb_feedback.from_id
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public Integer getFromId() {
		return fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_feedback.from_id
	 * @param fromId  the value for tb_feedback.from_id
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public void setFromId(Integer fromId) {
		this.fromId = fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_feedback.status
	 * @return  the value of tb_feedback.status
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_feedback.status
	 * @param status  the value for tb_feedback.status
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_feedback.create_time
	 * @return  the value of tb_feedback.create_time
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_feedback.create_time
	 * @param createTime  the value for tb_feedback.create_time
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_feedback.update_time
	 * @return  the value of tb_feedback.update_time
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_feedback.update_time
	 * @param updateTime  the value for tb_feedback.update_time
	 * @mbggenerated  Sun Aug 24 10:29:02 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}