package com.bruce.designer.model;

import java.util.Date;

public class IndexSlide {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_index_slide.id
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_index_slide.code
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_index_slide.sort
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_index_slide.status
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_index_slide.create_time
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_index_slide.update_time
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_index_slide.id
	 * @return  the value of tb_index_slide.id
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_index_slide.id
	 * @param id  the value for tb_index_slide.id
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_index_slide.code
	 * @return  the value of tb_index_slide.code
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_index_slide.code
	 * @param code  the value for tb_index_slide.code
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_index_slide.sort
	 * @return  the value of tb_index_slide.sort
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_index_slide.sort
	 * @param sort  the value for tb_index_slide.sort
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_index_slide.status
	 * @return  the value of tb_index_slide.status
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_index_slide.status
	 * @param status  the value for tb_index_slide.status
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_index_slide.create_time
	 * @return  the value of tb_index_slide.create_time
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_index_slide.create_time
	 * @param createTime  the value for tb_index_slide.create_time
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_index_slide.update_time
	 * @return  the value of tb_index_slide.update_time
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_index_slide.update_time
	 * @param updateTime  the value for tb_index_slide.update_time
	 * @mbggenerated  Sun Aug 24 23:39:46 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}