package com.bruce.designer.model;

import java.util.Date;

public class Tag extends TagBase{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag.id
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag.name
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag.status
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag.create_time
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag.update_time
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag.id
	 * @return  the value of tb_tag.id
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag.id
	 * @param id  the value for tb_tag.id
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag.name
	 * @return  the value of tb_tag.name
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag.name
	 * @param name  the value for tb_tag.name
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag.status
	 * @return  the value of tb_tag.status
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag.status
	 * @param status  the value for tb_tag.status
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag.create_time
	 * @return  the value of tb_tag.create_time
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag.create_time
	 * @param createTime  the value for tb_tag.create_time
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag.update_time
	 * @return  the value of tb_tag.update_time
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag.update_time
	 * @param updateTime  the value for tb_tag.update_time
	 * @mbggenerated  Sun Aug 24 10:50:48 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}