package com.bruce.designer.model;

import java.util.Date;

public class TagAlbum {
	
	private Album album;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag_album.id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag_album.tag_id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	private Integer tagId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag_album.album_id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag_album.create_time
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_tag_album.update_time
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag_album.id
	 * @return  the value of tb_tag_album.id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag_album.id
	 * @param id  the value for tb_tag_album.id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag_album.tag_id
	 * @return  the value of tb_tag_album.tag_id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public Integer getTagId() {
		return tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag_album.tag_id
	 * @param tagId  the value for tb_tag_album.tag_id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag_album.album_id
	 * @return  the value of tb_tag_album.album_id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag_album.album_id
	 * @param albumId  the value for tb_tag_album.album_id
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag_album.create_time
	 * @return  the value of tb_tag_album.create_time
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag_album.create_time
	 * @param createTime  the value for tb_tag_album.create_time
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_tag_album.update_time
	 * @return  the value of tb_tag_album.update_time
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_tag_album.update_time
	 * @param updateTime  the value for tb_tag_album.update_time
	 * @mbggenerated  Tue Nov 12 15:42:42 CST 2013
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Album getAlbum() {
		return album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}
	
	
}