package com.bruce.designer.model;

import java.util.Date;

public class UserFans {
    
    private User fansUser;
    
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_fans.id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_fans.user_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_fans.fans_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Integer fansId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_fans.create_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_fans.update_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_fans.id
     * @return  the value of tb_user_fans.id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_fans.id
     * @param id  the value for tb_user_fans.id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_fans.user_id
     * @return  the value of tb_user_fans.user_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_fans.user_id
     * @param userId  the value for tb_user_fans.user_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_fans.fans_id
     * @return  the value of tb_user_fans.fans_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Integer getFansId() {
        return fansId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_fans.fans_id
     * @param fansId  the value for tb_user_fans.fans_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setFansId(Integer fansId) {
        this.fansId = fansId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_fans.create_time
     * @return  the value of tb_user_fans.create_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_fans.create_time
     * @param createTime  the value for tb_user_fans.create_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_fans.update_time
     * @return  the value of tb_user_fans.update_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_fans.update_time
     * @param updateTime  the value for tb_user_fans.update_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public User getFansUser() {
        return fansUser;
    }

    public void setFansUser(User fansUser) {
        this.fansUser = fansUser;
    }
    
    
}