package com.bruce.designer.model;

import java.util.Date;

public class UserPushToken {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.user_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.os_type
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private Short osType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.push_channel_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private Long pushChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.push_user_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private String pushUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.status
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.create_time
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_push_token.update_time
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.id
	 * @return  the value of tb_user_push_token.id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.id
	 * @param id  the value for tb_user_push_token.id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.user_id
	 * @return  the value of tb_user_push_token.user_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.user_id
	 * @param userId  the value for tb_user_push_token.user_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.os_type
	 * @return  the value of tb_user_push_token.os_type
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public Short getOsType() {
		return osType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.os_type
	 * @param osType  the value for tb_user_push_token.os_type
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setOsType(Short osType) {
		this.osType = osType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.push_channel_id
	 * @return  the value of tb_user_push_token.push_channel_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public Long getPushChannelId() {
		return pushChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.push_channel_id
	 * @param pushChannelId  the value for tb_user_push_token.push_channel_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setPushChannelId(Long pushChannelId) {
		this.pushChannelId = pushChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.push_user_id
	 * @return  the value of tb_user_push_token.push_user_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public String getPushUserId() {
		return pushUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.push_user_id
	 * @param pushUserId  the value for tb_user_push_token.push_user_id
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setPushUserId(String pushUserId) {
		this.pushUserId = pushUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.status
	 * @return  the value of tb_user_push_token.status
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.status
	 * @param status  the value for tb_user_push_token.status
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.create_time
	 * @return  the value of tb_user_push_token.create_time
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.create_time
	 * @param createTime  the value for tb_user_push_token.create_time
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_push_token.update_time
	 * @return  the value of tb_user_push_token.update_time
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_push_token.update_time
	 * @param updateTime  the value for tb_user_push_token.update_time
	 * @mbggenerated  Wed Nov 12 11:17:18 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}