package com.bruce.designer.model;

import java.util.Date;

public class VersionUpdate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.id
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.client_type
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private Short clientType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.channel
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.version_code
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private Integer versionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.version_name
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String versionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.version_title
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String versionTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.version_description
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String versionDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.release_note
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String releaseNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.update_status
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private Short updateStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.update_url
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String updateUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.agree_text
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String agreeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.denied_text
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private String deniedText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.create_time
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_version_update.update_time
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.id
	 * @return  the value of tb_version_update.id
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.id
	 * @param id  the value for tb_version_update.id
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.client_type
	 * @return  the value of tb_version_update.client_type
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public Short getClientType() {
		return clientType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.client_type
	 * @param clientType  the value for tb_version_update.client_type
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setClientType(Short clientType) {
		this.clientType = clientType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.channel
	 * @return  the value of tb_version_update.channel
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.channel
	 * @param channel  the value for tb_version_update.channel
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.version_code
	 * @return  the value of tb_version_update.version_code
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public Integer getVersionCode() {
		return versionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.version_code
	 * @param versionCode  the value for tb_version_update.version_code
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setVersionCode(Integer versionCode) {
		this.versionCode = versionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.version_name
	 * @return  the value of tb_version_update.version_name
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getVersionName() {
		return versionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.version_name
	 * @param versionName  the value for tb_version_update.version_name
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.version_title
	 * @return  the value of tb_version_update.version_title
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getVersionTitle() {
		return versionTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.version_title
	 * @param versionTitle  the value for tb_version_update.version_title
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setVersionTitle(String versionTitle) {
		this.versionTitle = versionTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.version_description
	 * @return  the value of tb_version_update.version_description
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getVersionDescription() {
		return versionDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.version_description
	 * @param versionDescription  the value for tb_version_update.version_description
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setVersionDescription(String versionDescription) {
		this.versionDescription = versionDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.release_note
	 * @return  the value of tb_version_update.release_note
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getReleaseNote() {
		return releaseNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.release_note
	 * @param releaseNote  the value for tb_version_update.release_note
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setReleaseNote(String releaseNote) {
		this.releaseNote = releaseNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.update_status
	 * @return  the value of tb_version_update.update_status
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public Short getUpdateStatus() {
		return updateStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.update_status
	 * @param updateStatus  the value for tb_version_update.update_status
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setUpdateStatus(Short updateStatus) {
		this.updateStatus = updateStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.update_url
	 * @return  the value of tb_version_update.update_url
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getUpdateUrl() {
		return updateUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.update_url
	 * @param updateUrl  the value for tb_version_update.update_url
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setUpdateUrl(String updateUrl) {
		this.updateUrl = updateUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.agree_text
	 * @return  the value of tb_version_update.agree_text
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getAgreeText() {
		return agreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.agree_text
	 * @param agreeText  the value for tb_version_update.agree_text
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setAgreeText(String agreeText) {
		this.agreeText = agreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.denied_text
	 * @return  the value of tb_version_update.denied_text
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public String getDeniedText() {
		return deniedText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.denied_text
	 * @param deniedText  the value for tb_version_update.denied_text
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setDeniedText(String deniedText) {
		this.deniedText = deniedText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.create_time
	 * @return  the value of tb_version_update.create_time
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.create_time
	 * @param createTime  the value for tb_version_update.create_time
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_version_update.update_time
	 * @return  the value of tb_version_update.update_time
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_version_update.update_time
	 * @param updateTime  the value for tb_version_update.update_time
	 * @mbggenerated  Wed Nov 19 15:22:18 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}