package com.bruce.designer.model;

import java.util.Date;

public class Vote {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.id
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.title
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.description
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.thumb_pic_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private String thumbPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.pic_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.sort
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.max_check_limit
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Integer maxCheckLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.max_repeat_limit
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Integer maxRepeatLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.vote_start_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Date voteStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.vote_end_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Date voteEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private String wxShareTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private String wxShareContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private String wxShareIconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.status
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.create_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vote.update_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.id
	 * @return  the value of tb_vote.id
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.id
	 * @param id  the value for tb_vote.id
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.title
	 * @return  the value of tb_vote.title
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.title
	 * @param title  the value for tb_vote.title
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.description
	 * @return  the value of tb_vote.description
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.description
	 * @param description  the value for tb_vote.description
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.thumb_pic_url
	 * @return  the value of tb_vote.thumb_pic_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public String getThumbPicUrl() {
		return thumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.thumb_pic_url
	 * @param thumbPicUrl  the value for tb_vote.thumb_pic_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setThumbPicUrl(String thumbPicUrl) {
		this.thumbPicUrl = thumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.pic_url
	 * @return  the value of tb_vote.pic_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.pic_url
	 * @param picUrl  the value for tb_vote.pic_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.sort
	 * @return  the value of tb_vote.sort
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.sort
	 * @param sort  the value for tb_vote.sort
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.max_check_limit
	 * @return  the value of tb_vote.max_check_limit
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Integer getMaxCheckLimit() {
		return maxCheckLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.max_check_limit
	 * @param maxCheckLimit  the value for tb_vote.max_check_limit
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setMaxCheckLimit(Integer maxCheckLimit) {
		this.maxCheckLimit = maxCheckLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.max_repeat_limit
	 * @return  the value of tb_vote.max_repeat_limit
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Integer getMaxRepeatLimit() {
		return maxRepeatLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.max_repeat_limit
	 * @param maxRepeatLimit  the value for tb_vote.max_repeat_limit
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setMaxRepeatLimit(Integer maxRepeatLimit) {
		this.maxRepeatLimit = maxRepeatLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.vote_start_time
	 * @return  the value of tb_vote.vote_start_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Date getVoteStartTime() {
		return voteStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.vote_start_time
	 * @param voteStartTime  the value for tb_vote.vote_start_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setVoteStartTime(Date voteStartTime) {
		this.voteStartTime = voteStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.vote_end_time
	 * @return  the value of tb_vote.vote_end_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Date getVoteEndTime() {
		return voteEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.vote_end_time
	 * @param voteEndTime  the value for tb_vote.vote_end_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setVoteEndTime(Date voteEndTime) {
		this.voteEndTime = voteEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.wx_share_title
	 * @return  the value of tb_vote.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public String getWxShareTitle() {
		return wxShareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.wx_share_title
	 * @param wxShareTitle  the value for tb_vote.wx_share_title
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setWxShareTitle(String wxShareTitle) {
		this.wxShareTitle = wxShareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.wx_share_content
	 * @return  the value of tb_vote.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public String getWxShareContent() {
		return wxShareContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.wx_share_content
	 * @param wxShareContent  the value for tb_vote.wx_share_content
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setWxShareContent(String wxShareContent) {
		this.wxShareContent = wxShareContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.wx_share_icon_url
	 * @return  the value of tb_vote.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public String getWxShareIconUrl() {
		return wxShareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.wx_share_icon_url
	 * @param wxShareIconUrl  the value for tb_vote.wx_share_icon_url
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setWxShareIconUrl(String wxShareIconUrl) {
		this.wxShareIconUrl = wxShareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.status
	 * @return  the value of tb_vote.status
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.status
	 * @param status  the value for tb_vote.status
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.create_time
	 * @return  the value of tb_vote.create_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.create_time
	 * @param createTime  the value for tb_vote.create_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vote.update_time
	 * @return  the value of tb_vote.update_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vote.update_time
	 * @param updateTime  the value for tb_vote.update_time
	 * @mbggenerated  Tue Dec 09 18:56:09 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}