package com.bruce.designer.admin.dao.security;

import com.bruce.designer.admin.bean.security.AdminRoleResource;
import com.bruce.designer.admin.bean.security.AdminRoleResourceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminRoleResourceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int countByExample(AdminRoleResourceCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int deleteByExample(AdminRoleResourceCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int insert(AdminRoleResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int insertSelective(AdminRoleResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	List<AdminRoleResource> selectByExample(AdminRoleResourceCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	AdminRoleResource selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int updateByExampleSelective(@Param("record") AdminRoleResource record,
			@Param("example") AdminRoleResourceCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int updateByExample(@Param("record") AdminRoleResource record,
			@Param("example") AdminRoleResourceCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int updateByPrimaryKeySelective(AdminRoleResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role_resource
	 * @mbggenerated  Fri Jul 26 23:55:51 CST 2013
	 */
	int updateByPrimaryKey(AdminRoleResource record);
}