package com.bruce.designer.admin.dao.security;

import com.bruce.designer.admin.bean.security.AdminRole;
import com.bruce.designer.admin.bean.security.AdminRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int countByExample(AdminRoleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int deleteByExample(AdminRoleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int insert(AdminRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int insertSelective(AdminRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	List<AdminRole> selectByExample(AdminRoleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	AdminRole selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int updateByExampleSelective(@Param("record") AdminRole record,
			@Param("example") AdminRoleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int updateByExample(@Param("record") AdminRole record,
			@Param("example") AdminRoleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int updateByPrimaryKeySelective(AdminRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_role
	 * @mbggenerated  Wed Jul 17 10:25:15 CST 2013
	 */
	int updateByPrimaryKey(AdminRole record);
}