package com.bruce.designer.admin.dao.security;

import com.bruce.designer.admin.bean.security.AdminUserRole;
import com.bruce.designer.admin.bean.security.AdminUserRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminUserRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int countByExample(AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int deleteByExample(AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int insert(AdminUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int insertSelective(AdminUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    List<AdminUserRole> selectByExample(AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    AdminUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int updateByExampleSelective(@Param("record") AdminUserRole record,
            @Param("example") AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int updateByExample(@Param("record") AdminUserRole record,
            @Param("example") AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int updateByPrimaryKeySelective(AdminUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Fri Jul 26 12:10:20 CST 2013
     */
    int updateByPrimaryKey(AdminUserRole record);
}