package com.bruce.designer.bean;

import java.util.Date;

public class Designer {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.id
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.user_id
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.id_num
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private String idNum;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.realname
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private String realname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.mobile
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private String mobile;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.company
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private String company;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.taobao_homepage
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private String taobaoHomepage;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.create_time
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.update_time
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_designer.status
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.id
     * @return  the value of tb_designer.id
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.id
     * @param id  the value for tb_designer.id
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.user_id
     * @return  the value of tb_designer.user_id
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.user_id
     * @param userId  the value for tb_designer.user_id
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.id_num
     * @return  the value of tb_designer.id_num
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.id_num
     * @param idNum  the value for tb_designer.id_num
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.realname
     * @return  the value of tb_designer.realname
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.realname
     * @param realname  the value for tb_designer.realname
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.mobile
     * @return  the value of tb_designer.mobile
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.mobile
     * @param mobile  the value for tb_designer.mobile
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.company
     * @return  the value of tb_designer.company
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.company
     * @param company  the value for tb_designer.company
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.taobao_homepage
     * @return  the value of tb_designer.taobao_homepage
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public String getTaobaoHomepage() {
        return taobaoHomepage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.taobao_homepage
     * @param taobaoHomepage  the value for tb_designer.taobao_homepage
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setTaobaoHomepage(String taobaoHomepage) {
        this.taobaoHomepage = taobaoHomepage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.create_time
     * @return  the value of tb_designer.create_time
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.create_time
     * @param createTime  the value for tb_designer.create_time
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.update_time
     * @return  the value of tb_designer.update_time
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.update_time
     * @param updateTime  the value for tb_designer.update_time
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_designer.status
     * @return  the value of tb_designer.status
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_designer.status
     * @param status  the value for tb_designer.status
     * @mbggenerated  Thu Sep 05 17:17:07 CST 2013
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}