package com.bruce.designer.bean;

import java.util.Date;

public class TbAlbum extends TbAlbumBase{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.remark
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album.cover_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String coverImg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.id
	 * @return  the value of tb_album.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.id
	 * @param id  the value for tb_album.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.title
	 * @return  the value of tb_album.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.title
	 * @param title  the value for tb_album.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.remark
	 * @return  the value of tb_album.remark
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.remark
	 * @param remark  the value for tb_album.remark
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.user_id
	 * @return  the value of tb_album.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.user_id
	 * @param userId  the value for tb_album.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.create_time
	 * @return  the value of tb_album.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.create_time
	 * @param createTime  the value for tb_album.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.update_time
	 * @return  the value of tb_album.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.update_time
	 * @param updateTime  the value for tb_album.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.status
	 * @return  the value of tb_album.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.status
	 * @param status  the value for tb_album.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album.cover_img
	 * @return  the value of tb_album.cover_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getCoverImg() {
		return coverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album.cover_img
	 * @param coverImg  the value for tb_album.cover_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setCoverImg(String coverImg) {
		this.coverImg = coverImg;
	}
}