package com.bruce.designer.bean;

import java.util.Date;

public class TbAlbumContent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.remark
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.album_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_content.content_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String contentImg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.id
	 * @return  the value of tb_album_content.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.id
	 * @param id  the value for tb_album_content.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.title
	 * @return  the value of tb_album_content.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.title
	 * @param title  the value for tb_album_content.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.remark
	 * @return  the value of tb_album_content.remark
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.remark
	 * @param remark  the value for tb_album_content.remark
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.album_id
	 * @return  the value of tb_album_content.album_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.album_id
	 * @param albumId  the value for tb_album_content.album_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.user_id
	 * @return  the value of tb_album_content.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.user_id
	 * @param userId  the value for tb_album_content.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.create_time
	 * @return  the value of tb_album_content.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.create_time
	 * @param createTime  the value for tb_album_content.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.update_time
	 * @return  the value of tb_album_content.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.update_time
	 * @param updateTime  the value for tb_album_content.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.status
	 * @return  the value of tb_album_content.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.status
	 * @param status  the value for tb_album_content.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_content.content_img
	 * @return  the value of tb_album_content.content_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getContentImg() {
		return contentImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_content.content_img
	 * @param contentImg  the value for tb_album_content.content_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setContentImg(String contentImg) {
		this.contentImg = contentImg;
	}
}