package com.bruce.designer.bean;

import java.util.Date;

public class TbComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.id
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.title
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.comment
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.user_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.create_time
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.update_time
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.status
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.album_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.album_content_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private Integer albumContentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.user_head_img
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private String userHeadImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.nickname
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	private String nickname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.id
	 * @return  the value of tb_comment.id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.id
	 * @param id  the value for tb_comment.id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.title
	 * @return  the value of tb_comment.title
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.title
	 * @param title  the value for tb_comment.title
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.comment
	 * @return  the value of tb_comment.comment
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.comment
	 * @param comment  the value for tb_comment.comment
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.user_id
	 * @return  the value of tb_comment.user_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.user_id
	 * @param userId  the value for tb_comment.user_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.create_time
	 * @return  the value of tb_comment.create_time
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.create_time
	 * @param createTime  the value for tb_comment.create_time
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.update_time
	 * @return  the value of tb_comment.update_time
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.update_time
	 * @param updateTime  the value for tb_comment.update_time
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.status
	 * @return  the value of tb_comment.status
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.status
	 * @param status  the value for tb_comment.status
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.album_id
	 * @return  the value of tb_comment.album_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.album_id
	 * @param albumId  the value for tb_comment.album_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.album_content_id
	 * @return  the value of tb_comment.album_content_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public Integer getAlbumContentId() {
		return albumContentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.album_content_id
	 * @param albumContentId  the value for tb_comment.album_content_id
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setAlbumContentId(Integer albumContentId) {
		this.albumContentId = albumContentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.user_head_img
	 * @return  the value of tb_comment.user_head_img
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public String getUserHeadImg() {
		return userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.user_head_img
	 * @param userHeadImg  the value for tb_comment.user_head_img
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public void setUserHeadImg(String userHeadImg) {
		this.userHeadImg = userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.nickname
	 * @return  the value of tb_comment.nickname
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.nickname
	 * @param nickname  the value for tb_comment.nickname
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.comment
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.album_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.album_content_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private Integer albumContentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.user_head_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String userHeadImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.nickname
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	private String nickname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.id
	 * @return  the value of tb_comment.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.id
	 * @param id  the value for tb_comment.id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.title
	 * @return  the value of tb_comment.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.title
	 * @param title  the value for tb_comment.title
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.comment
	 * @return  the value of tb_comment.comment
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.comment
	 * @param comment  the value for tb_comment.comment
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.user_id
	 * @return  the value of tb_comment.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.user_id
	 * @param userId  the value for tb_comment.user_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.create_time
	 * @return  the value of tb_comment.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.create_time
	 * @param createTime  the value for tb_comment.create_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.update_time
	 * @return  the value of tb_comment.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.update_time
	 * @param updateTime  the value for tb_comment.update_time
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.status
	 * @return  the value of tb_comment.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.status
	 * @param status  the value for tb_comment.status
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.album_id
	 * @return  the value of tb_comment.album_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.album_id
	 * @param albumId  the value for tb_comment.album_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.album_content_id
	 * @return  the value of tb_comment.album_content_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public Integer getAlbumContentId() {
		return albumContentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.album_content_id
	 * @param albumContentId  the value for tb_comment.album_content_id
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setAlbumContentId(Integer albumContentId) {
		this.albumContentId = albumContentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.user_head_img
	 * @return  the value of tb_comment.user_head_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getUserHeadImg() {
		return userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.user_head_img
	 * @param userHeadImg  the value for tb_comment.user_head_img
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public void setUserHeadImg(String userHeadImg) {
		this.userHeadImg = userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.nickname
	 * @return  the value of tb_comment.nickname
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.nickname
	 * @param nickname  the value for tb_comment.nickname
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
}
