package com.bruce.designer.bean;

import java.util.Date;

public class User extends UserBase{

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.id
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.nickname
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String nickname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.username
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.password
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.email
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String email;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.create_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.update_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.status
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private Short status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.head_img
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String headImg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_status
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private Short designerStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_identifer
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String designerIdentifer;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_realname
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String designerRealname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_mobile
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String designerMobile;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_introduction
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String designerIntroduction;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_company
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String designerCompany;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_taobao_homepage
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private String designerTaobaoHomepage;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_apply_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private Date designerApplyTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.designer_pass_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    private Date designerPassTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.id
     * @return  the value of tb_user.id
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.id
     * @param id  the value for tb_user.id
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.nickname
     * @return  the value of tb_user.nickname
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.nickname
     * @param nickname  the value for tb_user.nickname
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.username
     * @return  the value of tb_user.username
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.username
     * @param username  the value for tb_user.username
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.password
     * @return  the value of tb_user.password
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.password
     * @param password  the value for tb_user.password
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.email
     * @return  the value of tb_user.email
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.email
     * @param email  the value for tb_user.email
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.create_time
     * @return  the value of tb_user.create_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.create_time
     * @param createTime  the value for tb_user.create_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.update_time
     * @return  the value of tb_user.update_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.update_time
     * @param updateTime  the value for tb_user.update_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.status
     * @return  the value of tb_user.status
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.status
     * @param status  the value for tb_user.status
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.head_img
     * @return  the value of tb_user.head_img
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.head_img
     * @param headImg  the value for tb_user.head_img
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_status
     * @return  the value of tb_user.designer_status
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public Short getDesignerStatus() {
        return designerStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_status
     * @param designerStatus  the value for tb_user.designer_status
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerStatus(Short designerStatus) {
        this.designerStatus = designerStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_identifer
     * @return  the value of tb_user.designer_identifer
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getDesignerIdentifer() {
        return designerIdentifer;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_identifer
     * @param designerIdentifer  the value for tb_user.designer_identifer
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerIdentifer(String designerIdentifer) {
        this.designerIdentifer = designerIdentifer;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_realname
     * @return  the value of tb_user.designer_realname
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getDesignerRealname() {
        return designerRealname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_realname
     * @param designerRealname  the value for tb_user.designer_realname
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerRealname(String designerRealname) {
        this.designerRealname = designerRealname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_mobile
     * @return  the value of tb_user.designer_mobile
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getDesignerMobile() {
        return designerMobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_mobile
     * @param designerMobile  the value for tb_user.designer_mobile
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerMobile(String designerMobile) {
        this.designerMobile = designerMobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_introduction
     * @return  the value of tb_user.designer_introduction
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getDesignerIntroduction() {
        return designerIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_introduction
     * @param designerIntroduction  the value for tb_user.designer_introduction
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerIntroduction(String designerIntroduction) {
        this.designerIntroduction = designerIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_company
     * @return  the value of tb_user.designer_company
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getDesignerCompany() {
        return designerCompany;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_company
     * @param designerCompany  the value for tb_user.designer_company
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerCompany(String designerCompany) {
        this.designerCompany = designerCompany;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_taobao_homepage
     * @return  the value of tb_user.designer_taobao_homepage
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public String getDesignerTaobaoHomepage() {
        return designerTaobaoHomepage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_taobao_homepage
     * @param designerTaobaoHomepage  the value for tb_user.designer_taobao_homepage
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerTaobaoHomepage(String designerTaobaoHomepage) {
        this.designerTaobaoHomepage = designerTaobaoHomepage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_apply_time
     * @return  the value of tb_user.designer_apply_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public Date getDesignerApplyTime() {
        return designerApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_apply_time
     * @param designerApplyTime  the value for tb_user.designer_apply_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerApplyTime(Date designerApplyTime) {
        this.designerApplyTime = designerApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.designer_pass_time
     * @return  the value of tb_user.designer_pass_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public Date getDesignerPassTime() {
        return designerPassTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.designer_pass_time
     * @param designerPassTime  the value for tb_user.designer_pass_time
     * @mbggenerated  Fri Sep 06 12:04:18 CST 2013
     */
    public void setDesignerPassTime(Date designerPassTime) {
        this.designerPassTime = designerPassTime;
    }
}