package com.bruce.designer.bean;

import java.util.Date;

public class User extends UserBase{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.id
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.username
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.password
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.email
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.create_time
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.update_time
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.status
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.head_img
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private String headImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.nickname
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	private String nickname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.id
	 * @return  the value of tb_user.id
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.id
	 * @param id  the value for tb_user.id
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.username
	 * @return  the value of tb_user.username
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.username
	 * @param username  the value for tb_user.username
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.password
	 * @return  the value of tb_user.password
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.password
	 * @param password  the value for tb_user.password
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.email
	 * @return  the value of tb_user.email
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.email
	 * @param email  the value for tb_user.email
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.create_time
	 * @return  the value of tb_user.create_time
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.create_time
	 * @param createTime  the value for tb_user.create_time
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.update_time
	 * @return  the value of tb_user.update_time
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.update_time
	 * @param updateTime  the value for tb_user.update_time
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.status
	 * @return  the value of tb_user.status
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.status
	 * @param status  the value for tb_user.status
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.head_img
	 * @return  the value of tb_user.head_img
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public String getHeadImg() {
		return headImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.head_img
	 * @param headImg  the value for tb_user.head_img
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.nickname
	 * @return  the value of tb_user.nickname
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.nickname
	 * @param nickname  the value for tb_user.nickname
	 * @mbggenerated  Sat Jul 06 00:08:54 CST 2013
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
}