package com.bruce.designer.model.zc;

import java.util.Date;

public class FeedDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feed.id
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feed.user_id
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feed.content
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feed.create_time
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feed.update_time
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feed.id
     *
     * @return the value of tb_feed.id
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feed.id
     *
     * @param id the value for tb_feed.id
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feed.user_id
     *
     * @return the value of tb_feed.user_id
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feed.user_id
     *
     * @param userId the value for tb_feed.user_id
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feed.content
     *
     * @return the value of tb_feed.content
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feed.content
     *
     * @param content the value for tb_feed.content
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feed.create_time
     *
     * @return the value of tb_feed.create_time
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feed.create_time
     *
     * @param createTime the value for tb_feed.create_time
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feed.update_time
     *
     * @return the value of tb_feed.update_time
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feed.update_time
     *
     * @param updateTime the value for tb_feed.update_time
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}