package com.bruce.designer.dao.mapper;

import com.bruce.designer.model.AlbumCounter;
import com.bruce.designer.model.AlbumCounterCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumCounterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int countByExample(AlbumCounterCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int deleteByExample(AlbumCounterCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int insert(AlbumCounter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int insertSelective(AlbumCounter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	List<AlbumCounter> selectByExample(AlbumCounterCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	AlbumCounter selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AlbumCounter record, @Param("example") AlbumCounterCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int updateByExample(@Param("record") AlbumCounter record, @Param("example") AlbumCounterCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int updateByPrimaryKeySelective(AlbumCounter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_counter
	 * @mbggenerated  Sun Feb 16 10:16:39 CST 2014
	 */
	int updateByPrimaryKey(AlbumCounter record);
}