package com.bruce.designer.dao.mapper;

import com.bruce.designer.data.CountCacheBean;
import com.bruce.designer.model.AlbumActionLog;
import com.bruce.designer.model.AlbumActionLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumActionLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int countByExample(AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int deleteByExample(AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int insert(AlbumActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int insertSelective(AlbumActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	List<AlbumActionLog> selectByExample(AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	AlbumActionLog selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AlbumActionLog record, @Param("example") AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int updateByExample(@Param("record") AlbumActionLog record, @Param("example") AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int updateByPrimaryKeySelective(AlbumActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Wed Feb 26 00:04:05 CST 2014
	 */
	int updateByPrimaryKey(AlbumActionLog record);
	
	List<CountCacheBean> queryBrowseStat();
	
	List<CountCacheBean> realtimeDailyTopAlbums(int limit);
	
	List<CountCacheBean> realtimeWeeklyTopAlbums(int limit);
	
	List<CountCacheBean> realtimeMonthlyTopAlbums(int limit);
	
	List<CountCacheBean> realtimeDailyTopDesigners(int limit);
    
    List<CountCacheBean> realtimeWeeklyTopDesigners(int limit);
    
    List<CountCacheBean> realtimeMonthlyTopDesigners(int limit);

//	List<CountCacheBean> queryFavoriteData();
}