package com.bruce.designer.dao.mapper;

import com.bruce.designer.model.AlbumSlide;
import com.bruce.designer.model.AlbumSlideCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumSlideMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int countByExample(AlbumSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int deleteByExample(AlbumSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int insert(AlbumSlide record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int insertSelective(AlbumSlide record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	List<AlbumSlide> selectByExample(AlbumSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	AlbumSlide selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AlbumSlide record, @Param("example") AlbumSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int updateByExample(@Param("record") AlbumSlide record, @Param("example") AlbumSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int updateByPrimaryKeySelective(AlbumSlide record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
	 * @mbggenerated  Sun Aug 24 10:26:59 CST 2014
	 */
	int updateByPrimaryKey(AlbumSlide record);
}