package com.bruce.designer.dao.mapper;

import com.bruce.designer.data.CountCacheBean;
import com.bruce.designer.model.AlbumActionLog;
import com.bruce.designer.model.AlbumActionLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumActionLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int countByExample(AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int deleteByExample(AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int insert(AlbumActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int insertSelective(AlbumActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	List<AlbumActionLog> selectByExample(AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	AlbumActionLog selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AlbumActionLog record, @Param("example") AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int updateByExample(@Param("record") AlbumActionLog record, @Param("example") AlbumActionLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int updateByPrimaryKeySelective(AlbumActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_action_log
	 * @mbggenerated  Sun Aug 24 10:14:06 CST 2014
	 */
	int updateByPrimaryKey(AlbumActionLog record);

	List<CountCacheBean> queryBrowseStat();
	
	List<CountCacheBean> realtimeDailyTopAlbums(AlbumActionLogCriteria example);
	
	List<CountCacheBean> realtimeWeeklyTopAlbums(AlbumActionLogCriteria example);
	
	List<CountCacheBean> realtimeMonthlyTopAlbums(AlbumActionLogCriteria example);
	
	List<CountCacheBean> realtimeYearlyTopAlbums(AlbumActionLogCriteria example);
	
	List<CountCacheBean> realtimeDailyTopDesigners(AlbumActionLogCriteria example);
    
    List<CountCacheBean> realtimeWeeklyTopDesigners(AlbumActionLogCriteria example);
    
    List<CountCacheBean> realtimeMonthlyTopDesigners(AlbumActionLogCriteria example);
    
    List<CountCacheBean> realtimeYearlyTopDesigners(AlbumActionLogCriteria example);

//	List<CountCacheBean> queryFavoriteData();
}