package com.bruce.designer.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bruce.designer.data.CountCacheBean;
import com.bruce.designer.model.Comment;
import com.bruce.designer.model.CommentCriteria;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int countByExample(CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int deleteByExample(CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	List<Comment> selectByExample(CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	Comment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int updateByExample(@Param("record") Comment record, @Param("example") CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Sun Aug 24 23:34:56 CST 2014
	 */
	int updateByPrimaryKey(Comment record);

	/**
	 * ???å»ºç??è®¡æ?°æ??
	 * @return
	 */
	List<CountCacheBean> queryCommentStat();
}