package com.bruce.designer.dao.mapper;

import com.bruce.designer.model.IndexSlide;
import com.bruce.designer.model.IndexSlideCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexSlideMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int countByExample(IndexSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int deleteByExample(IndexSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int insert(IndexSlide record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int insertSelective(IndexSlide record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	List<IndexSlide> selectByExample(IndexSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	IndexSlide selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int updateByExampleSelective(@Param("record") IndexSlide record, @Param("example") IndexSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int updateByExample(@Param("record") IndexSlide record, @Param("example") IndexSlideCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int updateByPrimaryKeySelective(IndexSlide record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_index_slide
	 * @mbggenerated  Sun Aug 24 14:24:08 CST 2014
	 */
	int updateByPrimaryKey(IndexSlide record);
}