package com.bruce.designer.dao.mapper;

import com.bruce.designer.model.Message;
import com.bruce.designer.model.MessageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {
    
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int countByExample(MessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int deleteByExample(MessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	List<Message> selectByExample(MessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	Message selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int updateByExample(@Param("record") Message record, @Param("example") MessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
	 * @mbggenerated  Sun Aug 24 23:36:54 CST 2014
	 */
	int updateByPrimaryKey(Message record);

	List<Message> queryMessageSummary(int userId);
}