package com.bruce.designer.dao.mapper;

import com.bruce.designer.model.UserFan;
import com.bruce.designer.model.UserFanCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int countByExample(UserFanCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int deleteByExample(UserFanCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int insert(UserFan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int insertSelective(UserFan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	List<UserFan> selectByExample(UserFanCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	UserFan selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int updateByExampleSelective(@Param("record") UserFan record, @Param("example") UserFanCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int updateByExample(@Param("record") UserFan record, @Param("example") UserFanCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int updateByPrimaryKeySelective(UserFan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_fan
	 * @mbggenerated  Sun Aug 24 10:57:27 CST 2014
	 */
	int updateByPrimaryKey(UserFan record);
}