package com.bruce.designer.dao.mapper;

import com.bruce.designer.model.UserFan;
import com.bruce.designer.model.UserFanCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int countByExample(UserFanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int deleteByExample(UserFanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int insert(UserFan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int insertSelective(UserFan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    List<UserFan> selectByExample(UserFanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    UserFan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") UserFan record, @Param("example") UserFanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int updateByExample(@Param("record") UserFan record, @Param("example") UserFanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int updateByPrimaryKeySelective(UserFan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_fan
     *
     * @mbggenerated Sat Oct 12 19:09:06 CST 2013
     */
    int updateByPrimaryKey(UserFan record);
}