package com.bruce.designer.dao.mapper;

import com.bruce.designer.data.CountCacheBean;
import com.bruce.designer.model.VoteResult;
import com.bruce.designer.model.VoteResultCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int countByExample(VoteResultCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int deleteByExample(VoteResultCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int insert(VoteResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int insertSelective(VoteResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	List<VoteResult> selectByExample(VoteResultCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	VoteResult selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") VoteResult record,
			@Param("example") VoteResultCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int updateByExample(@Param("record") VoteResult record,
			@Param("example") VoteResultCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int updateByPrimaryKeySelective(VoteResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote_result
	 * @mbggenerated  Wed Dec 31 14:23:17 CST 2014
	 */
	int updateByPrimaryKey(VoteResult record);

	List<CountCacheBean> queryVoteResultStat(@Param("voteId")int voteId); 
}