package com.bruce.designer.dao.mapper;

import com.bruce.designer.model.Vote;
import com.bruce.designer.model.VoteCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int countByExample(VoteCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int deleteByExample(VoteCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int insert(Vote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int insertSelective(Vote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	List<Vote> selectByExample(VoteCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	Vote selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Vote record,
			@Param("example") VoteCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int updateByExample(@Param("record") Vote record,
			@Param("example") VoteCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int updateByPrimaryKeySelective(Vote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	int updateByPrimaryKey(Vote record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_vote
	 * @mbggenerated  Mon Dec 08 18:35:33 CST 2014
	 */
	Vote loadByOptionId(int optionId);
}