package com.bruce.designer.dao;

import com.bruce.designer.bean.AlbumSlide;
import com.bruce.designer.bean.AlbumSlideCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumSlideMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int countByExample(AlbumSlideCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int deleteByExample(AlbumSlideCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int insert(AlbumSlide record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int insertSelective(AlbumSlide record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    List<AlbumSlide> selectByExample(AlbumSlideCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    AlbumSlide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int updateByExampleSelective(@Param("record") AlbumSlide record,
            @Param("example") AlbumSlideCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int updateByExample(@Param("record") AlbumSlide record,
            @Param("example") AlbumSlideCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int updateByPrimaryKeySelective(AlbumSlide record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_album_slide
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    int updateByPrimaryKey(AlbumSlide record);
}