package com.bruce.designer.dao;

import com.bruce.designer.model.Comment;
import com.bruce.designer.model.CommentCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int countByExample(CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int deleteByExample(CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	List<Comment> selectByExample(CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	Comment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Comment record,
			@Param("example") CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int updateByExample(@Param("record") Comment record,
			@Param("example") CommentCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	int updateByPrimaryKey(Comment record);
}