package com.bruce.designer.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bruce.designer.model.FeedDTO;
import com.bruce.designer.model.FeedDTOCriteria;

public interface FeedDTOMapper {

    List<FeedDTO> getFeedsByIds(List<Long> ids);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int countByExample(FeedDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int deleteByExample(FeedDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int insert(FeedDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int insertSelective(FeedDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    List<FeedDTO> selectByExample(FeedDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    FeedDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int updateByExampleSelective(@Param("record") FeedDTO record, @Param("example") FeedDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int updateByExample(@Param("record") FeedDTO record, @Param("example") FeedDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int updateByPrimaryKeySelective(FeedDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feed
     *
     * @mbggenerated Sun Sep 22 19:33:31 CST 2013
     */
    int updateByPrimaryKey(FeedDTO record);
}