package com.bruce.designer.dao;

import com.bruce.designer.bean.TbDesigner;
import com.bruce.designer.bean.TbDesignerCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDesignerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int countByExample(TbDesignerCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int deleteByExample(TbDesignerCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int insert(TbDesigner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int insertSelective(TbDesigner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	List<TbDesigner> selectByExample(TbDesignerCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	TbDesigner selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TbDesigner record,
			@Param("example") TbDesignerCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int updateByExample(@Param("record") TbDesigner record,
			@Param("example") TbDesignerCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int updateByPrimaryKeySelective(TbDesigner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_designer
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
	 */
	int updateByPrimaryKey(TbDesigner record);
}