package com.bruce.designer.dao;

import com.bruce.designer.bean.TbMessage;
import com.bruce.designer.bean.TbMessageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int countByExample(TbMessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int deleteByExample(TbMessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int insert(TbMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int insertSelective(TbMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	List<TbMessage> selectByExample(TbMessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	TbMessage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int updateByExampleSelective(@Param("record") TbMessage record,
			@Param("example") TbMessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int updateByExample(@Param("record") TbMessage record,
			@Param("example") TbMessageCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int updateByPrimaryKeySelective(TbMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_message
<<<<<<< HEAD
	 * @mbggenerated  Tue Jul 02 23:50:20 CST 2013
=======
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
>>>>>>> branch 'master' of https://github.com/liqian008/designer.git
	 */
	int updateByPrimaryKey(TbMessage record);
}
