package com.bruce.designer.dao;

import com.bruce.designer.bean.TbUser;
import com.bruce.designer.bean.TbUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int countByExample(TbUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int deleteByExample(TbUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int insert(TbUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int insertSelective(TbUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	List<TbUser> selectByExample(TbUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	TbUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TbUser record,
			@Param("example") TbUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int updateByExample(@Param("record") TbUser record,
			@Param("example") TbUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int updateByPrimaryKeySelective(TbUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Tue Jul 02 16:51:08 CST 2013
	 */
	int updateByPrimaryKey(TbUser record);
    
//    TbUser selectByUsernameAndPasswd(Object username, Object password);
    
    
}