package com.bruce.designer.dao;

import com.bruce.designer.model.UserFollow;
import com.bruce.designer.model.UserFollowCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFollowMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int countByExample(UserFollowCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int deleteByExample(UserFollowCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int insert(UserFollow record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int insertSelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    List<UserFollow> selectByExample(UserFollowCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    UserFollow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int updateByExampleSelective(@Param("record") UserFollow record,
            @Param("example") UserFollowCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int updateByExample(@Param("record") UserFollow record,
            @Param("example") UserFollowCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int updateByPrimaryKeySelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_follow
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    int updateByPrimaryKey(UserFollow record);
}