package com.bruce.designer.admin.bean.security;

import java.util.Date;
import java.util.List;

public class AdminRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.id
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.rolename
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.status
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.create_time
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.update_time
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    private Date updateTime;
    
    private List<AdminMenu> adminMenus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.id
     *
     * @return the value of admin_role.id
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.id
     *
     * @param id the value for admin_role.id
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.rolename
     *
     * @return the value of admin_role.rolename
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.rolename
     *
     * @param rolename the value for admin_role.rolename
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.status
     *
     * @return the value of admin_role.status
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.status
     *
     * @param status the value for admin_role.status
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.create_time
     *
     * @return the value of admin_role.create_time
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.create_time
     *
     * @param createTime the value for admin_role.create_time
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.update_time
     *
     * @return the value of admin_role.update_time
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.update_time
     *
     * @param updateTime the value for admin_role.update_time
     *
     * @mbggenerated Wed Jul 17 10:25:15 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public List<AdminMenu> getAdminMenus() {
		return adminMenus;
	}

	public void setAdminMenus(List<AdminMenu> adminMenus) {
		this.adminMenus = adminMenus;
	}
    
    
}